const INITIAL_STOCKS = [
    { name: "Aurion Motors", symbol: "AUR", sector: "EV", ipoPrice: 120, volatility: 0.35, trendBias: "bullish", currentPrice: 120 },
    { name: "Nebula Cloud", symbol: "NEB", sector: "Tech", ipoPrice: 450, volatility: 0.25, trendBias: "bullish", currentPrice: 450 },
    { name: "Titan Steel", symbol: "TIT", sector: "Industry", ipoPrice: 85, volatility: 0.15, trendBias: "neutral", currentPrice: 85 },
    { name: "Veridian Agri", symbol: "VER", sector: "Agro", ipoPrice: 45, volatility: 0.20, trendBias: "bullish", currentPrice: 45 },
    { name: "Xenon Pharma", symbol: "XEN", sector: "Health", ipoPrice: 210, volatility: 0.30, trendBias: "bullish", currentPrice: 210 },
    { name: "Solaris Energy", symbol: "SOL", sector: "Energy", ipoPrice: 160, volatility: 0.40, trendBias: "bullish", currentPrice: 160 },
    { name: "AeroJet Systems", symbol: "AJS", sector: "Aero", ipoPrice: 320, volatility: 0.28, trendBias: "neutral", currentPrice: 320 },
    { name: "Biolume Corp", symbol: "BIO", sector: "Health", ipoPrice: 95, volatility: 0.45, trendBias: "bearish", currentPrice: 95 },
    { name: "CyberNode", symbol: "CYB", sector: "Tech", ipoPrice: 550, volatility: 0.35, trendBias: "bullish", currentPrice: 550 },
    { name: "DuraBuild", symbol: "DUR", sector: "Cons", ipoPrice: 65, volatility: 0.12, trendBias: "neutral", currentPrice: 65 },
    { name: "EcoStream", symbol: "ECO", sector: "Energy", ipoPrice: 110, volatility: 0.33, trendBias: "bullish", currentPrice: 110 },
    { name: "Fusion Rail", symbol: "FUS", sector: "Trans", ipoPrice: 140, volatility: 0.18, trendBias: "bullish", currentPrice: 140 },
    { name: "GigaChips", symbol: "GIG", sector: "Tech", ipoPrice: 720, volatility: 0.38, trendBias: "bullish", currentPrice: 720 },
    { name: "HydraWater", symbol: "HYD", sector: "Util", ipoPrice: 30, volatility: 0.10, trendBias: "neutral", currentPrice: 30 },
    { name: "Ion Battery", symbol: "ION", sector: "EV", ipoPrice: 190, volatility: 0.42, trendBias: "bullish", currentPrice: 190 },
    { name: "Jupiter Media", symbol: "JUP", sector: "Ent", ipoPrice: 250, volatility: 0.22, trendBias: "neutral", currentPrice: 250 },
    { name: "Kinetix Robotics", symbol: "KIN", sector: "Tech", ipoPrice: 380, volatility: 0.40, trendBias: "bullish", currentPrice: 380 },
    { name: "Luna Textiles", symbol: "LUN", sector: "Retail", ipoPrice: 55, volatility: 0.15, trendBias: "bearish", currentPrice: 55 },
    { name: "Magma Mining", symbol: "MAG", sector: "Mining", ipoPrice: 130, volatility: 0.30, trendBias: "neutral", currentPrice: 130 },
    { name: "Nova Fintech", symbol: "NOV", sector: "Fin", ipoPrice: 290, volatility: 0.25, trendBias: "bullish", currentPrice: 290 },
    { name: "Oasis Dev", symbol: "OAS", sector: "Real", ipoPrice: 175, volatility: 0.20, trendBias: "neutral", currentPrice: 175 },
    { name: "Peak Foods", symbol: "PEA", sector: "FMCG", ipoPrice: 90, volatility: 0.14, trendBias: "bullish", currentPrice: 90 },
    { name: "Quantum Sec", symbol: "QUA", sector: "Tech", ipoPrice: 420, volatility: 0.35, trendBias: "bullish", currentPrice: 420 },
    { name: "Radian Optics", symbol: "RAD", sector: "Tech", ipoPrice: 115, volatility: 0.28, trendBias: "neutral", currentPrice: 115 },
    { name: "Stellar Hotels", symbol: "STE", sector: "Hosp", ipoPrice: 205, volatility: 0.18, trendBias: "bearish", currentPrice: 205 },
    { name: "Terra Logistics", symbol: "TER", sector: "Trans", ipoPrice: 125, volatility: 0.22, trendBias: "bullish", currentPrice: 125 },
    { name: "Urban Smart", symbol: "URB", sector: "Cons", ipoPrice: 80, volatility: 0.24, trendBias: "neutral", currentPrice: 80 },
    { name: "Vortex Labs", symbol: "VOR", sector: "Bio", ipoPrice: 310, volatility: 0.45, trendBias: "bullish", currentPrice: 310 },
    { name: "WindForce", symbol: "WND", sector: "Energy", ipoPrice: 145, volatility: 0.32, trendBias: "bullish", currentPrice: 145 },
    { name: "Xylem Water", symbol: "XYL", sector: "Util", ipoPrice: 40, volatility: 0.12, trendBias: "neutral", currentPrice: 40 },
    { name: "Yield Agro", symbol: "YLD", sector: "Agro", ipoPrice: 75, volatility: 0.20, trendBias: "bullish", currentPrice: 75 },
    { name: "Zenith Glass", symbol: "ZEN", sector: "Ind", ipoPrice: 110, volatility: 0.16, trendBias: "neutral", currentPrice: 110 },
    { name: "Aria Airways", symbol: "ARI", sector: "Aero", ipoPrice: 350, volatility: 0.26, trendBias: "bearish", currentPrice: 350 },
    { name: "Beacon Bank", symbol: "BEA", sector: "Fin", ipoPrice: 180, volatility: 0.14, trendBias: "bullish", currentPrice: 180 },
    { name: "Crest Chemicals", symbol: "CRE", sector: "Ind", ipoPrice: 135, volatility: 0.22, trendBias: "neutral", currentPrice: 135 },
    { name: "Delta Data", symbol: "DEL", sector: "Tech", ipoPrice: 260, volatility: 0.30, trendBias: "bullish", currentPrice: 260 },
    { name: "Eris Fashion", symbol: "ERI", sector: "Retail", ipoPrice: 95, volatility: 0.35, trendBias: "bearish", currentPrice: 95 },
    { name: "Flux Mob", symbol: "FLX", sector: "EV", ipoPrice: 215, volatility: 0.40, trendBias: "bullish", currentPrice: 215 },
    { name: "Glacier Ice", symbol: "GLA", sector: "Log", ipoPrice: 60, volatility: 0.18, trendBias: "neutral", currentPrice: 60 },
    { name: "Halo Software", symbol: "HAL", sector: "Tech", ipoPrice: 480, volatility: 0.24, trendBias: "bullish", currentPrice: 480 },
    { name: "Infinity Al", symbol: "INF", sector: "Tech", ipoPrice: 600, volatility: 0.50, trendBias: "bullish", currentPrice: 600 },
    { name: "Jade Jewels", symbol: "JAD", sector: "Lux", ipoPrice: 410, volatility: 0.20, trendBias: "neutral", currentPrice: 410 },
    { name: "Krypton Labs", symbol: "KRY", sector: "Bio", ipoPrice: 195, volatility: 0.38, trendBias: "bullish", currentPrice: 195 },
    { name: "Lyra Music", symbol: "LYR", sector: "Ent", ipoPrice: 120, volatility: 0.28, trendBias: "bearish", currentPrice: 120 },
    { name: "Maximus Brew", symbol: "MAX", sector: "FMCG", ipoPrice: 70, volatility: 0.15, trendBias: "bullish", currentPrice: 70 },
    { name: "Nexus Network", symbol: "NEX", sector: "Comm", ipoPrice: 330, volatility: 0.25, trendBias: "neutral", currentPrice: 330 },
    { name: "Omnistack", symbol: "OMN", sector: "SaaS", ipoPrice: 275, volatility: 0.22, trendBias: "bullish", currentPrice: 275 },
    { name: "Pulse Health", symbol: "PUL", sector: "Health", ipoPrice: 155, volatility: 0.18, trendBias: "bullish", currentPrice: 155 },
    { name: "Quasar Space", symbol: "QSR", sector: "Aero", ipoPrice: 520, volatility: 0.45, trendBias: "bullish", currentPrice: 520 },
    { name: "Rifting Oil", symbol: "RIF", sector: "Energy", ipoPrice: 190, volatility: 0.35, trendBias: "bearish", currentPrice: 190 }
];

export default INITIAL_STOCKS;
